#####################################生产版配置####################################
spring:
  #配置数据源
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/template?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
  #redis配置
  redis:
    #索引(默认为0)
    database: 7
    host: 127.0.0.1
    port: 6379
    #password: 123456
    #连接超时时间
    timeout: 10000ms