#############################################通用配置#############################################
server:
  port: 8080
spring:
  profiles:
    include: common-dev
mybatis:
  #设置MyBatis全局变量
  configuration-properties:
    # 文件存放域名前缀
    filePathPrefix: http://127.0.0.1:8080
  configuration:
    #IDEA的MyBatis Log插件以及控制台sql打印,dev打包部署不注释该代码，sql不会保存到日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#禁用swagger,
knife4j:
  production: false

#自定义全局变量*******注意:  :后面要有空格
global:
  #日志文件存放路径
  log-path: F:\Workspaces\weiziplus\github\springboot\demo-pc\target\logs
  #图片存放路径--本地项目运行的target目录
  base-file-path: F:\Workspaces\weiziplus\github\springboot\demo-pc\target\classes\static
  #允许跨域地址(访问的浏览器的Origin,不设置默认*)---多个地址用,(英文逗号)分隔开---可精确到端口号
  cors-filter-origins: '*'
  #是否將异常详情展示给前端
  response-show-runtime-exception: true
  #是否开启时间戳校验
  check-timeStamp: false